export const FETCH_ITEMS_REQUESTED = 'FETCH_ITEMS_REQUESTED'
export const FETCH_ITEMS_SUCCEEDED = 'FETCH_ITEMS_SUCCEEDED'
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const NEXT_WEEK = 'NEXT_WEEK'
export const PREVIOUS_WEEK = 'PREVIOUS_WEEK'
